apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: '{{ microservice.name }}'
      hasuraService: custom
    name: '{{ microservice.name }}'
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: '{{ microservice.name }}'
      spec:
        containers:
        - image: hasura/base-git-image:0.7
          imagePullPolicy: IfNotPresent
          name: '{{ microservice.name }}'
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: '{{ microservice.name }}'
      hasuraService: custom
    name: '{{ microservice.name }}'
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: '{{ microservice.name }}'
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
